# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00c4ea8cb56c09b4482d150a3bcfc6dc9d8d9d5029b58982f8138d9988fce7e2a2b6d7adf74d19a5b0956424ff380bb1f4c244342390e36085ec93588893fc64

test:
  secret_key_base: 9a9a250e9add610cc01040f28db159cd6a2f2d8775525bf2950da18a3a617f3b0654ed496b087d5606b633a743c29a06788ca834de1d0c81a900883e48a5cf27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
